import type { Metadata } from "next"
import { Nunito, Nunito_Sans } from "next/font/google"
import { SessionProvider } from "@/components/providers/SessionProvider"
import NextTopLoader from "nextjs-toploader"
import "./globals.css"

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
})

const nunitoSans = Nunito_Sans({
    variable: "--font-nunito-sans",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${nunito.variable} ${nunitoSans.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <NextTopLoader color="#1B4B8A" />
                <SessionProvider>{children}</SessionProvider>
            </body>
        </html>
    )
}
